### ISSUE TITLE
Controller shouldn't recieve I/O

### ISSUE THREAD

**Issue by NicolasLahsen** [tomasmetroy/IIC374-Grupo4#16]
The controller recieves input in method `request input`. That should be responsability of the view.
![image](https://user-images.githubusercontent.com/42189930/134956741-e22ab16c-7733-4d56-9804-58f6ba09c9b7.png)

An easy fix is create a simple view function that recieves the input, and let the controller call that function through the view

**Comment by diegomendieta** [comment]
Should be fixed in #25.
