### ISSUE TITLE
Board Model shoudn't print directly to console

### ISSUE THREAD

**Issue by NicolasLahsen** [tomasmetroy/IIC374-Grupo4#9]
En la línea 118 del archivo` board_model.rb` contiene un puts, cuando debería hacer una llamada a la vista, y que esta se encargue de imprimir en consola.

![image](https://user-images.githubusercontent.com/42189930/134777117-b36b7b15-442e-4920-ba53-f4db9116db6e.png)

Lo ideal sería hacer una función que retorne ese string, y luego hacer puts a esa función

**Comment by diegomendieta** [comment]
Should be fixed by #26.
